# -*- coding: utf-8 -*-
"""Audit Report Tracker — 3 levels, per-consolidation-level readiness status.
Extracted from the client Audit Report Tracker (reporting date 25 Apr 2026)."""

INFO = {'title': 'Audit Report Tracker',
 'reporting_date': '25 Apr 2026',
 'total': 80,
 'note': 'Report-readiness across consolidation levels. Levels 1–2 are produced in the Consolidation section (linked, '
         'not duplicated).'}

LEVEL_TITLES = {1: 'Financial Statement Level Reports',
 2: 'Notes to the Income Statement & Balance Sheet',
 3: 'Subledger / Detailed Data Level Reports'}

SCOPES = ['OIC Consolidation (branch-wise)',
 'OIC Consolidation (without OPI and RESL)',
 'OIC Consolidation (with OPI and RESL)',
 'OTF Consolidation (OTF & OTS)',
 'OIG Consolidation',
 'OIG Zakat Consolidation (100%-owned companies)',
 'OIG Standalone']

STATUS_COLS = [{'key': 'oig', 'label': 'OIG Consol Level'},
 {'key': 'oic', 'label': 'OIC Consol Level'},
 {'key': 'dv', 'label': 'Data Validation'}]

ITEMS = [{'sno': '1.1',
  'num': '1',
  'level': 1,
  'name': 'Income Statement (Current Year vs. Prior Year)',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': 'Incorrect data',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '1.2',
  'num': '2',
  'level': 1,
  'name': 'Balance Sheet (Current Year vs. Prior Year)',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': 'Incorrect data',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '1.3', 'num': '3', 'level': 1, 'name': 'Cash Flow Statement', 'oig': '', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Consolidation'},
 {'sno': '1.4',
  'num': '4',
  'level': 1,
  'name': 'Statement of Changes in Equity / Notes to Equity',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': 'Incorrect data',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '2.1',
  'num': '5',
  'level': 2,
  'name': 'Property, plant and equipment, Schedule by category',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': '',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '2.2', 'num': '6', 'level': 2, 'name': 'PPE to cost centre allocation for note (depreciation Exp)', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.3', 'num': '7', 'level': 2, 'name': 'Right of use assets, net and lease obligations', 'oig': '', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Consolidation'},
 {'sno': '2.4', 'num': '8', 'level': 2, 'name': 'Investment properties, (only ORE)', 'oig': '', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Consolidation'},
 {'sno': '2.5', 'num': '9', 'level': 2, 'name': 'Financial investments/Instruments - Total (only OIG_210)', 'oig': '', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Consolidation'},
 {'sno': '2.6', 'num': '10', 'level': 2, 'name': 'Intangible assets & Goodwill', 'oig': '', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Consolidation'},
 {'sno': '2.7',
  'num': '11',
  'level': 2,
  'name': 'Related Party Transaction listing',
  'oig': '',
  'oic': 'Future Project for IT',
  'dv': 'Future Project for IT',
  'overall': 'Future',
  'covered': 'Consolidation'},
 {'sno': '2.8',
  'num': '12',
  'level': 2,
  'name': 'Due From/To related party balance : Non eliminating',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': '',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '2.9',
  'num': '13',
  'level': 2,
  'name': 'Due From/To related party balance - Net off balance (Eliminating)',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': 'Not Available',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '2.10', 'num': '14', 'level': 2, 'name': 'Inventory by Group/Type summary', 'oig': '', 'oic': 'Incorrect data', 'dv': '', 'overall': 'Blocked', 'covered': 'Consolidation'},
 {'sno': '2.11', 'num': '15', 'level': 2, 'name': 'Contract assets report', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.12', 'num': '16', 'level': 2, 'name': 'Loan summary Note - STL / LTL and SIDF', 'oig': 'On-Hold', 'oic': '', 'dv': '', 'overall': 'Blocked', 'covered': 'Consolidation'},
 {'sno': '2.13', 'num': '17', 'level': 2, 'name': 'AR net, prepaid expenses and others current assets', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.14', 'num': '18', 'level': 2, 'name': 'AP, accruals, and others', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.15',
  'num': '19',
  'level': 2,
  'name': 'Zakat provision and Income Tax ( Full movement)',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': '',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '2.16', 'num': '20', 'level': 2, 'name': 'Cost of revenue expenses', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.17', 'num': '21', 'level': 2, 'name': 'Selling and distribution expenses', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.18', 'num': '22', 'level': 2, 'name': 'General and administration expenses', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.19', 'num': '23', 'level': 2, 'name': 'Finance costs', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.20', 'num': '24', 'level': 2, 'name': 'Other income', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '2.21', 'num': '25', 'level': 2, 'name': 'Non-Controlling Interest', 'oig': '', 'oic': 'Not applicable', 'dv': 'Not applicable', 'overall': 'N/A', 'covered': 'Consolidation'},
 {'sno': '2.22',
  'num': '26',
  'level': 2,
  'name': 'Segment report (cluster by IFRS)',
  'oig': '',
  'oic': 'Not Available at all',
  'dv': 'Not applicable',
  'overall': 'Blocked',
  'covered': 'Consolidation'},
 {'sno': '2.23', 'num': '27', 'level': 2, 'name': 'Cash and Cash Equivariant', 'oig': '', 'oic': '', 'dv': '', 'overall': 'Ready', 'covered': 'Consolidation'},
 {'sno': '3.1', 'num': '28', 'level': 3, 'name': 'Accounts Receivable (AR) Aging Report', 'oig': '', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.2', 'num': '29', 'level': 3, 'name': 'Advance by Customer and Unallocated', 'oig': '', 'oic': 'Not Available at all', 'dv': 'Not Available', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.3', 'num': '30', 'level': 3, 'name': 'ECL Schedule (IFRS 9)', 'oig': 'Not applicable', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.4', 'num': '31', 'level': 3, 'name': 'Customer movement (A/R - movements)', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.5', 'num': '32', 'level': 3, 'name': 'Statement of Accounts (SOA) A/R', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.6', 'num': '33', 'level': 3, 'name': 'Accounts Payable (AP) Aging Report', 'oig': 'On-Hold', 'oic': '', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.7', 'num': '34', 'level': 3, 'name': 'Advance by Supplier and Unallocated', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.8', 'num': '35', 'level': 3, 'name': 'Supplier movement (A/P - movements)', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.9', 'num': '36', 'level': 3, 'name': 'Statement of Accounts (SOA) - A/P', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.10', 'num': '37', 'level': 3, 'name': 'Purchase Analysis by Supplier/Summary', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.11', 'num': '38', 'level': 3, 'name': 'Sales by customer by details', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.12', 'num': '39', 'level': 3, 'name': 'Exceptional Report (AR Subledger Vs TB vs SoA) - Controls', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.13', 'num': '40', 'level': 3, 'name': 'Exceptional Report - Sales Report vs TB - Controls', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.14', 'num': '41', 'level': 3, 'name': 'Exceptional Report - AP Subledger Vs TB vs SoA - Controls', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.15',
  'num': '42',
  'level': 3,
  'name': 'Exceptional Report - VAT Return Vs Sub-ledger - Controls Not',
  'oig': '',
  'oic': 'OIC need to confirm',
  'dv': '',
  'overall': 'Query',
  'covered': 'Box 4'},
 {'sno': '3.16',
  'num': '43',
  'level': 3,
  'name': 'VAT Return Input and Output by Category',
  'oig': 'On-Hold',
  'oic': 'Not Available at all',
  'dv': 'OIC need to confirm',
  'overall': 'Blocked',
  'covered': 'Box 4'},
 {'sno': '3.17', 'num': '44', 'level': 3, 'name': 'Sales Report vs. Output VAT recon. (with listing of all doc)', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.18', 'num': '45', 'level': 3, 'name': 'VAT Report vs Ledger (with listing of all doc)', 'oig': 'Not applicable', 'oic': '', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.19', 'num': '46', 'level': 3, 'name': 'VAT on Advances (separate report)', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.20', 'num': '47', 'level': 3, 'name': 'Purchase Report vs. Input VAT recon.', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.21', 'num': '48', 'level': 3, 'name': 'Exceptional Report (Negative Fixed Assets)', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.22', 'num': '49', 'level': 3, 'name': 'FA Movement Report by GL/Assets', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.23', 'num': '50', 'level': 3, 'name': 'Inventory Aging Report', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': 'Incorrect data', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.24',
  'num': '51',
  'level': 3,
  'name': 'Inventory Valuation by Item (with cutoff date)',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': 'Incorrect data',
  'overall': 'Blocked',
  'covered': 'Box 4'},
 {'sno': '3.25',
  'num': '52',
  'level': 3,
  'name': 'Exceptional Report - Inventory Aging Report vs. TB Match',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': '',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.26', 'num': '53', 'level': 3, 'name': 'Inventory Movement Report', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.27', 'num': '54', 'level': 3, 'name': 'Item Movement Detail Report', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.28', 'num': '55', 'level': 3, 'name': 'Inventory Provision by Category', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.31',
  'num': '58',
  'level': 3,
  'name': 'Exceptional Report (Recon. of GL to All Subledger)',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': '',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.32', 'num': '59', 'level': 3, 'name': 'Intangible assets movement', 'oig': 'On-Hold', 'oic': 'Not applicable', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.33', 'num': '60', 'level': 3, 'name': 'Related party movement', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.34', 'num': '61', 'level': 3, 'name': 'FOREX movement report', 'oig': 'On-Hold', 'oic': 'Not applicable', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.35', 'num': '62', 'level': 3, 'name': 'Contract assets movements', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.36', 'num': '63', 'level': 3, 'name': 'Lease movement and schedules', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.37', 'num': '64', 'level': 3, 'name': 'Loan movement - STL / LTL / SIDF', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.38', 'num': '65', 'level': 3, 'name': 'Emp Cost recon. Sub ledger -End of service', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.39', 'num': '66', 'level': 3, 'name': 'Emp Cost recon. Sub ledger : Vacation', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.40', 'num': '67', 'level': 3, 'name': 'Emp Cost recon. Sub ledger: Ticket', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.41', 'num': '68', 'level': 3, 'name': 'Emp Cost recon. Sub ledger: Employee Loan', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.42', 'num': '69', 'level': 3, 'name': 'Bank Reconciliation (automation/download option)', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.43',
  'num': '70',
  'level': 3,
  'name': 'Intercompany reconciliation (automation/download option)',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': '',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.44',
  'num': '71',
  'level': 3,
  'name': 'Business Partner reconciliation (automation/download option)',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': '',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.45',
  'num': '72',
  'level': 3,
  'name': 'Intercompany Provision transfer (Emp. related details)',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': 'Not applicable',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.46',
  'num': '73',
  'level': 3,
  'name': 'Finance costs - movement report by Bank/Category',
  'oig': 'On-Hold',
  'oic': 'Not Available at all',
  'dv': '',
  'overall': 'Blocked',
  'covered': 'Box 4'},
 {'sno': '3.47', 'num': '74', 'level': 3, 'name': 'Other Income - Movement by Category', 'oig': 'On-Hold', 'oic': 'Not applicable', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.48', 'num': '75', 'level': 3, 'name': 'Cost center /Departmental reports (Expense)', 'oig': 'Not applicable', 'oic': 'Incorrect data', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.49', 'num': '76', 'level': 3, 'name': 'Trial Balance', 'oig': 'On-Hold', 'oic': 'Not Available at all', 'dv': 'Incorrect data', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.50', 'num': '77', 'level': 3, 'name': 'Customer Statement Auto-sending via agent', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.51',
  'num': '78',
  'level': 3,
  'name': 'Customer Balance Confirmation Letter send via agent',
  'oig': 'Not applicable',
  'oic': 'Not applicable',
  'dv': '',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.52', 'num': '79', 'level': 3, 'name': 'E-Invoice VAT report vs GL sales VAT Summary', 'oig': 'Not applicable', 'oic': 'Not applicable', 'dv': '', 'overall': 'N/A', 'covered': 'Box 4'},
 {'sno': '3.53', 'num': '80', 'level': 3, 'name': 'Employee Loan by Employee and by Company', 'oig': '', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'},
 {'sno': '3.54',
  'num': '81',
  'level': 3,
  'name': 'List of outstanding invoices for all receivables as at year end (invoice date, amount, receivable party)',
  'oig': '',
  'oic': 'Not applicable',
  'dv': '',
  'overall': 'N/A',
  'covered': 'Box 4'},
 {'sno': '3.55', 'num': '82', 'level': 3, 'name': 'Inventory balance Report - Next Tab', 'oig': '', 'oic': 'Not Available at all', 'dv': '', 'overall': 'Blocked', 'covered': 'Box 4'}]
